### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by anhnt-mageplaza** [usernam3/shopify-app-store-scraper#2]
First of all, thank you for supporting the community with this amazing work. I saw your work on Kaggle, I'm very impressed. I cloned the scraper to my local machine and give it a shot. However, I got the message `UnicodeEncodeError: 'charmap' codec can't encode characters` at `pipeline.py:93` and I found that we need to set the encoding of the open file like this: https://imgur.com/9m8p2aU

Once again, thank you for your good work!

## Expected Behavior
The logging should show no errors

## Actual Behavior
The logging keeps showing error message writing to file. 

## Steps to Reproduce the Problem
Just run `scrapy crawl app_store`

## Specifications

  - Python: 3.6 
  - Platform: Windows
  - Subsystem: None

**Comment by usernam3** [comment]
Hey @anhnt-mageplaza , thanks for reporting this one, nice catch! 🙇
