### ISSUE TITLE
App page has changed markup

### ISSUE THREAD

**Issue by tsirakis** [usernam3/shopify-app-store-scraper#3]
The app page html has changed so the scraper cannot find certain info.
The new css rules are:

title: '.vc-app-listing-hero__heading::text'
developer: '.vc-app-listing-hero__by-line a::text'
developer_linl: '.vc-app-listing-hero__by-line a::attr(href)'
icon: '.vc-app-listing-about-section__title img::attr(src)'
description_raw: '.vc-app-listing-about-section__description'
description: '.vc-app-listing-about-section__description::text'
tagline: '.vc-app-listing-hero__tagline::text'
pricing_hint: '.ui-app-pricing--format-detail::text'

Key Benefit: '.vc-app-listing-key-values__item'
Key Benefit Title: '.vc-app-listing-key-values__item-title'
Key Benefit Description: '.vc-app-listing-key-values__item-description'
Pricing Plan Title: '.pricing-plan-card__title-kicker.'
Pricing Plan Feature: '.ul li .bullet__content'
Category: '.vc-app-listing-hero__taxonomy-links a::text'

**Comment by usernam3** [comment]
And once again, thank you @tsirakis ! Merging to master.
