### ISSUE TITLE
scarper seems not working

### ISSUE THREAD

**Issue by PengW9996** [usernam3/shopify-app-store-scraper#8]
Hi, sorry for the interruption. I have a similar Shopify scraper, but Shopify seems to change the web scraping policy after March 03, 2022, which does not allow scraping some contents. I wonder that do you have similar issues?

**Comment by usernam3** [comment]
Hey @PengW9996 , thanks for writing!
Indeed, I just started scraper and noticed that sometimes it gets the `HTTP 429 Too Many Requests` instead of pages, following actions can help with it :
1) Lowering the `CONCURRENT_REQUESTS` setting
2) [Rotating IPs/using proxies and sending requests from different IP addresses](https://github.com/aivarsk/scrapy-proxies)

Can I ask which pages/contents you couldn't scrape, so that I will double-check them? (As **429** was the only issue that I ran into while testing. When the app/review page is there, data is properly collected, so I think that selectors didn't change)

**Comment by PengW9996** [comment]
About my scraper, I cannot obtain the review and some app page part. Btw, how can i use your scarper on python?

**Comment by PengW9996** [comment]
My scraper cannot obtain the reviews and some app pages parts.

**Comment by PengW9996** [comment]
After running your scraper, I have the same HTTP 429 Too Many Requests issues.

**Comment by PengW9996** [comment]
Btw, how to use proxies and sending requests from different IP addresses since I have use this before

**Comment by PengW9996** [comment]
Really thanks for your sharing and answering.

**Comment by guilhermeprokisch** [comment]
I'm also getting this errors. 

But actually I just want the last db version, Shopify seems to have 7096 apps today, but in Kaggle version just have 4000ish. Did you have a more recent db version @usernam3  

<img width="353" alt="Screen Shot 2022-04-30 at 18 19 22" src="https://user-images.githubusercontent.com/12011070/166123005-00fc2fe5-eb44-427a-94b5-a9b50a91d204.png">

**Comment by usernam3** [comment]
Hey @guilhermeprokisch 👋 
Thanks for writing, the thing is that the Shopify app store changed their scrapping policy (not sure exactly when), which
makes it a bit harder to scrape data from there. It is still possible if you limit the number of requests in combo with dynamic
IP addresses as I wrote up there ☝️ 
But currently, I am working on the version (FYI here #10), which makes spider more 'polite' and scrapes only the missing part
of data, which should significantly decrease the total number of requests and make the process resumable. Once it is done I will try to update the dataset on kaggle. Hope that will work 🤞 
Any contributions will be really helpful, so please feel free to join!

**Comment by guilhermeprokisch** [comment]
Fantastic @usernam3  Thanks you

**Comment by usernam3** [comment]
Hey @guilhermeprokisch, I will be wrapping up that PR soon, but you can already download the updated dataset [from kaggle](https://www.kaggle.com/datasets/usernam3/shopify-app-store)

**Comment by guilhermeprokisch** [comment]
Amazing! Thanks @usernam3

**Comment by guilhermeprokisch** [comment]
@usernam3  No rush on that...I'm trying to run again this notebook https://www.kaggle.com/code/guilhermeprokisch/shopify-app-store-overview/edit and seems that some databases do not have the same format as before.  Maybe you know answer me why. Thanks

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/12011070/172388543-5c36717e-0f0e-4cc9-a40e-31f2d2c4889d.png">

**Comment by usernam3** [comment]
@guilhermeprokisch Hey 👋 I think this can be related to the `apps.id` column, as now it is a primary key that should be used to join (`pd.merge`) data. In the old notebook, it was `apps.url <-> reviews.app_url` and `apps.url <-> categories.app_url`, not it is `apps.id <-> reviews.app_id` and `apps.id <-> categories.app_id`. Hope it helps!

**Comment by guilhermeprokisch** [comment]
@usernam3  but there's no categories.app_id. There's an `id` on  c `categories` but seems no related with apps. I wondering how to link the app dataset with categories ...
<img width="524" alt="image" src="https://user-images.githubusercontent.com/12011070/173462795-45d8174b-ae71-4083-8ed7-383538fe067b.png">

**Comment by usernam3** [comment]
You are right, sorry, I meant `apps.id <-> apps_categories.app_id` and then you can join data using `apps_categories.category_id <-> categories.id`

**Comment by usernam3** [comment]
Closing this issue as it was solved by [v2.1.0](https://github.com/usernam3/shopify-app-store-scraper/releases/tag/v2.1.0)
